Allow missing authentication method for overlay batch system
unibonn/puppet-cobald pull request #1
Opened 2020-10-21 07:37 UTC by stefan-k

First of all thanks for this module! 
In our setup, the overlay batch system runs locally, therefore (if I understand this correctly) we do not require authentication via `auth_obs`.
In this PR I've added a `none` switch which allows for bypassing the related section in `install.pp`. I don't know if this has other implications that I'm not aware of, as I currently can't test it because I first need to solve other unrelated problems ;)
It would be great if you could provide feedback to this PR. Feel free to reject it if it doesn't fit into the module.

2020-10-21 08:57 UTC, wiene reviewed
I wonder whether we should use `undef` to indicate the absence of an authentication mechanism rather than introducing a new type `none`.

2020-10-21 09:06 UTC, stefan-k commented
I'm fine with both options and I'm happy to provide an updated PR.

2020-10-21 09:08 UTC, wiene reviewed
@olifre: What do you think?

2020-10-21 10:21 UTC, olifre commented
> @olifre: What do you think?

I also think `undef` feels more natural, in fact, since we already have `Optional` for the class parameter, `undef` should ideally have a meaning ;-).

2020-10-21 11:19 UTC, stefan-k commented
Thanks for the feedback! I changed it accordingly. I needed to change the default value of `auth_obs` from `gsi` to `undef`, which may be a breaking change.

2020-10-21 11:44 UTC, wiene requested changes
Thanks for the updated PR. Despite of the breaking change, I think this solution is nicer.

Could you squash your commits before merging, please.

2020-10-21 11:58 UTC, stefan-k commented
I can certainly squash the commits, but then I have to force-push and the history will be lost. Is there a reason why you prefer manual squashing over Github's `Squash and merge` functionality?

2020-10-21 13:24 UTC, wiene commented
We prefer having a linear history with the intermediate steps from the drafting stage cleaned up. We also think that the PR author is the best person to write a concise summary of the intention and the contents of the PR.

2020-10-22 11:13 UTC, olifre approved these changes
That looks good to me :+1: .

2020-10-22 15:58 UTC, wiene approved these changes
Thanks for your contribution.

2020-10-22 15:59 UTC, merged